services:
  mariadb:
    image: mariadb:latest
    container_name: matsfx-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    attach: false


  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matsfx-app
    restart: always
    environment:
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: ${MYSQL_HOST}
    volumes:
      - .:/var/www/html
    ports:
      - "${PORT}:80"
    depends_on:
      - mariadb
    pull_policy: build

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: matsfx-phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PHPMYADMIN_PORT: ${PHPMYADMIN_PORT}
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_FORCE_SSL: false
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}
    depends_on:
      - mariadb
    restart: unless-stopped


volumes:
  mariadb_data: