name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Prepare Upload Directories
      run: |
        sudo mkdir -p ${{ github.workspace }}/uploads/covers
        sudo mkdir -p ${{ github.workspace }}/uploads/songs
        sudo mkdir -p ${{ github.workspace }}/uploads/profiles
        sudo chmod -R 777 ${{ github.workspace }}/uploads
